CREATE ROLE role_migrator;
CREATE ROLE role_app;

CREATE USER {{MIGRATOR_USER}} WITH PASSWORD '{{MIGRATOR_PASS}}';
CREATE USER {{APP_USER}} WITH PASSWORD '{{APP_PASS}}';

GRANT role_migrator TO {{MIGRATOR_USER}};
GRANT role_app TO {{APP_USER}};

GRANT CONNECT ON DATABASE "{{DB_NAME}}" TO role_migrator;
GRANT CONNECT ON DATABASE "{{DB_NAME}}" TO role_app;

\c "{{DB_NAME}}"

GRANT ALL ON SCHEMA public TO role_migrator;
GRANT USAGE ON SCHEMA public TO role_app;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO role_migrator;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO role_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO role_app;

ALTER DEFAULT PRIVILEGES FOR ROLE role_migrator IN SCHEMA public 
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO role_app;

ALTER DEFAULT PRIVILEGES FOR ROLE role_migrator IN SCHEMA public 
GRANT USAGE, SELECT ON SEQUENCES TO role_app;
