CREATE ROLE IF NOT EXISTS 'role_migrator', 'role_app';

GRANT ALL PRIVILEGES ON `{{DB_NAME}}`.* TO 'role_migrator';

GRANT SELECT, INSERT, UPDATE, DELETE ON `{{DB_NAME}}`.* TO 'role_app';

CREATE USER IF NOT EXISTS '{{MIGRATOR_USER}}'@'%' IDENTIFIED BY '{{MIGRATOR_PASS}}';
CREATE USER IF NOT EXISTS '{{APP_USER}}'@'%' IDENTIFIED BY '{{APP_PASS}}';

GRANT 'role_migrator' TO '{{MIGRATOR_USER}}'@'%';
GRANT 'role_app' TO '{{APP_USER}}'@'%';

SET DEFAULT ROLE ALL TO '{{MIGRATOR_USER}}'@'%', '{{APP_USER}}'@'%';

FLUSH PRIVILEGES;