// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package api is a generated GoMock package.
package api

import (
	context "context"
	http "net/http"
	reflect "reflect"
	datastruct "subscription-vault-service/internal/datastruct"

	gomock "github.com/golang/mock/gomock"
)

// MockIWithStatus is a mock of IWithStatus interface.
type MockIWithStatus struct {
	ctrl     *gomock.Controller
	recorder *MockIWithStatusMockRecorder
}

// MockIWithStatusMockRecorder is the mock recorder for MockIWithStatus.
type MockIWithStatusMockRecorder struct {
	mock *MockIWithStatus
}

// NewMockIWithStatus creates a new mock instance.
func NewMockIWithStatus(ctrl *gomock.Controller) *MockIWithStatus {
	mock := &MockIWithStatus{ctrl: ctrl}
	mock.recorder = &MockIWithStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIWithStatus) EXPECT() *MockIWithStatusMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockIWithStatus) GetStatus() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockIWithStatusMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockIWithStatus)(nil).GetStatus))
}

// MockISubscriptionService is a mock of ISubscriptionService interface.
type MockISubscriptionService struct {
	ctrl     *gomock.Controller
	recorder *MockISubscriptionServiceMockRecorder
}

// MockISubscriptionServiceMockRecorder is the mock recorder for MockISubscriptionService.
type MockISubscriptionServiceMockRecorder struct {
	mock *MockISubscriptionService
}

// NewMockISubscriptionService creates a new mock instance.
func NewMockISubscriptionService(ctrl *gomock.Controller) *MockISubscriptionService {
	mock := &MockISubscriptionService{ctrl: ctrl}
	mock.recorder = &MockISubscriptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISubscriptionService) EXPECT() *MockISubscriptionServiceMockRecorder {
	return m.recorder
}

// AddSubscription mocks base method.
func (m *MockISubscriptionService) AddSubscription(arg0 *datastruct.CreateSubscriptionRequest) *datastruct.CreateSubscriptionResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubscription", arg0)
	ret0, _ := ret[0].(*datastruct.CreateSubscriptionResponse)
	return ret0
}

// AddSubscription indicates an expected call of AddSubscription.
func (mr *MockISubscriptionServiceMockRecorder) AddSubscription(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubscription", reflect.TypeOf((*MockISubscriptionService)(nil).AddSubscription), arg0)
}

// CalculateSubscriptionsPrice mocks base method.
func (m *MockISubscriptionService) CalculateSubscriptionsPrice(arg0 *datastruct.CalculateSubscriptionsPriceRequest) *datastruct.CalculateSubscriptionsPriceResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateSubscriptionsPrice", arg0)
	ret0, _ := ret[0].(*datastruct.CalculateSubscriptionsPriceResponse)
	return ret0
}

// CalculateSubscriptionsPrice indicates an expected call of CalculateSubscriptionsPrice.
func (mr *MockISubscriptionServiceMockRecorder) CalculateSubscriptionsPrice(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateSubscriptionsPrice", reflect.TypeOf((*MockISubscriptionService)(nil).CalculateSubscriptionsPrice), arg0)
}

// DeleteSubscription mocks base method.
func (m *MockISubscriptionService) DeleteSubscription(arg0 *datastruct.DeleteSubscriptionRequest) *datastruct.DeleteSubscriptionResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubscription", arg0)
	ret0, _ := ret[0].(*datastruct.DeleteSubscriptionResponse)
	return ret0
}

// DeleteSubscription indicates an expected call of DeleteSubscription.
func (mr *MockISubscriptionServiceMockRecorder) DeleteSubscription(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubscription", reflect.TypeOf((*MockISubscriptionService)(nil).DeleteSubscription), arg0)
}

// GetSubscription mocks base method.
func (m *MockISubscriptionService) GetSubscription(arg0 *datastruct.GetSubscriptionRequest) *datastruct.GetSubscriptionResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscription", arg0)
	ret0, _ := ret[0].(*datastruct.GetSubscriptionResponse)
	return ret0
}

// GetSubscription indicates an expected call of GetSubscription.
func (mr *MockISubscriptionServiceMockRecorder) GetSubscription(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscription", reflect.TypeOf((*MockISubscriptionService)(nil).GetSubscription), arg0)
}

// ListSubscriptions mocks base method.
func (m *MockISubscriptionService) ListSubscriptions(arg0 *datastruct.ListSubscriptionsRequest) *datastruct.ListSubscriptionsResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptions", arg0)
	ret0, _ := ret[0].(*datastruct.ListSubscriptionsResponse)
	return ret0
}

// ListSubscriptions indicates an expected call of ListSubscriptions.
func (mr *MockISubscriptionServiceMockRecorder) ListSubscriptions(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptions", reflect.TypeOf((*MockISubscriptionService)(nil).ListSubscriptions), arg0)
}

// UpdateSubscription mocks base method.
func (m *MockISubscriptionService) UpdateSubscription(arg0 *datastruct.UpdateSubscriptionRequest) *datastruct.UpdateSubscriptionResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", arg0)
	ret0, _ := ret[0].(*datastruct.UpdateSubscriptionResponse)
	return ret0
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockISubscriptionServiceMockRecorder) UpdateSubscription(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockISubscriptionService)(nil).UpdateSubscription), arg0)
}

// MockISecretProvider is a mock of ISecretProvider interface.
type MockISecretProvider struct {
	ctrl     *gomock.Controller
	recorder *MockISecretProviderMockRecorder
}

// MockISecretProviderMockRecorder is the mock recorder for MockISecretProvider.
type MockISecretProviderMockRecorder struct {
	mock *MockISecretProvider
}

// NewMockISecretProvider creates a new mock instance.
func NewMockISecretProvider(ctrl *gomock.Controller) *MockISecretProvider {
	mock := &MockISecretProvider{ctrl: ctrl}
	mock.recorder = &MockISecretProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISecretProvider) EXPECT() *MockISecretProviderMockRecorder {
	return m.recorder
}

// ReadSecret mocks base method.
func (m *MockISecretProvider) ReadSecret(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadSecret", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadSecret indicates an expected call of ReadSecret.
func (mr *MockISecretProviderMockRecorder) ReadSecret(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadSecret", reflect.TypeOf((*MockISecretProvider)(nil).ReadSecret), key)
}

// MockIServer is a mock of IServer interface.
type MockIServer struct {
	ctrl     *gomock.Controller
	recorder *MockIServerMockRecorder
}

// MockIServerMockRecorder is the mock recorder for MockIServer.
type MockIServerMockRecorder struct {
	mock *MockIServer
}

// NewMockIServer creates a new mock instance.
func NewMockIServer(ctrl *gomock.Controller) *MockIServer {
	mock := &MockIServer{ctrl: ctrl}
	mock.recorder = &MockIServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServer) EXPECT() *MockIServerMockRecorder {
	return m.recorder
}

// ListenAndServe mocks base method.
func (m *MockIServer) ListenAndServe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServe")
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockIServerMockRecorder) ListenAndServe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServe", reflect.TypeOf((*MockIServer)(nil).ListenAndServe))
}

// Shutdown mocks base method.
func (m *MockIServer) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockIServerMockRecorder) Shutdown(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockIServer)(nil).Shutdown), ctx)
}

// MockIRouter is a mock of IRouter interface.
type MockIRouter struct {
	ctrl     *gomock.Controller
	recorder *MockIRouterMockRecorder
}

// MockIRouterMockRecorder is the mock recorder for MockIRouter.
type MockIRouterMockRecorder struct {
	mock *MockIRouter
}

// NewMockIRouter creates a new mock instance.
func NewMockIRouter(ctrl *gomock.Controller) *MockIRouter {
	mock := &MockIRouter{ctrl: ctrl}
	mock.recorder = &MockIRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRouter) EXPECT() *MockIRouterMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockIRouter) Handle(pattern string, handler http.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Handle", pattern, handler)
}

// Handle indicates an expected call of Handle.
func (mr *MockIRouterMockRecorder) Handle(pattern, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockIRouter)(nil).Handle), pattern, handler)
}

// ServeHTTP mocks base method.
func (m *MockIRouter) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ServeHTTP", w, r)
}

// ServeHTTP indicates an expected call of ServeHTTP.
func (mr *MockIRouterMockRecorder) ServeHTTP(w, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServeHTTP", reflect.TypeOf((*MockIRouter)(nil).ServeHTTP), w, r)
}

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// ErrorKV mocks base method.
func (m *MockILogger) ErrorKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorKV", varargs...)
}

// ErrorKV indicates an expected call of ErrorKV.
func (mr *MockILoggerMockRecorder) ErrorKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorKV", reflect.TypeOf((*MockILogger)(nil).ErrorKV), varargs...)
}

// FatalKV mocks base method.
func (m *MockILogger) FatalKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FatalKV", varargs...)
}

// FatalKV indicates an expected call of FatalKV.
func (mr *MockILoggerMockRecorder) FatalKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FatalKV", reflect.TypeOf((*MockILogger)(nil).FatalKV), varargs...)
}

// InfoKV mocks base method.
func (m *MockILogger) InfoKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoKV", varargs...)
}

// InfoKV indicates an expected call of InfoKV.
func (mr *MockILoggerMockRecorder) InfoKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoKV", reflect.TypeOf((*MockILogger)(nil).InfoKV), varargs...)
}

// WarnKV mocks base method.
func (m *MockILogger) WarnKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnKV", varargs...)
}

// WarnKV indicates an expected call of WarnKV.
func (mr *MockILoggerMockRecorder) WarnKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnKV", reflect.TypeOf((*MockILogger)(nil).WarnKV), varargs...)
}
