// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/google/uuid"
)

type Subscription struct {
	ID          int32
	UserUid     uuid.UUID
	ServiceName string
	Price       int64
	From        sql.NullTime
	To          sql.NullTime
}
