// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type Querier interface {
	CalculateSubscriptionsPrice(ctx context.Context, arg CalculateSubscriptionsPriceParams) (int64, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error
	DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) (sql.Result, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (GetSubscriptionRow, error)
	ListSubscriptions(ctx context.Context, userUid uuid.UUID) ([]ListSubscriptionsRow, error)
	UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
