// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
