// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions 
(user_uid, service_name, price, "from", "to") VALUES
($1, $2, $3, $4, $5)
ON CONFLICT (user_uid, service_name)
DO NOTHING
RETURNING user_uid
`

type CreateSubscriptionParams struct {
	UserUid     uuid.UUID
	ServiceName string
	Price       int64
	From        sql.NullTime
	To          sql.NullTime
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createSubscription,
		arg.UserUid,
		arg.ServiceName,
		arg.Price,
		arg.From,
		arg.To,
	)
	var user_uid uuid.UUID
	err := row.Scan(&user_uid)
	return user_uid, err
}
