// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// ErrorKV mocks base method.
func (m *MockILogger) ErrorKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ErrorKV", varargs...)
}

// ErrorKV indicates an expected call of ErrorKV.
func (mr *MockILoggerMockRecorder) ErrorKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ErrorKV", reflect.TypeOf((*MockILogger)(nil).ErrorKV), varargs...)
}

// FatalKV mocks base method.
func (m *MockILogger) FatalKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "FatalKV", varargs...)
}

// FatalKV indicates an expected call of FatalKV.
func (mr *MockILoggerMockRecorder) FatalKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FatalKV", reflect.TypeOf((*MockILogger)(nil).FatalKV), varargs...)
}

// InfoKV mocks base method.
func (m *MockILogger) InfoKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InfoKV", varargs...)
}

// InfoKV indicates an expected call of InfoKV.
func (mr *MockILoggerMockRecorder) InfoKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoKV", reflect.TypeOf((*MockILogger)(nil).InfoKV), varargs...)
}

// WarnKV mocks base method.
func (m *MockILogger) WarnKV(message string, argsKV ...any) {
	m.ctrl.T.Helper()
	varargs := []interface{}{message}
	for _, a := range argsKV {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "WarnKV", varargs...)
}

// WarnKV indicates an expected call of WarnKV.
func (mr *MockILoggerMockRecorder) WarnKV(message interface{}, argsKV ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{message}, argsKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WarnKV", reflect.TypeOf((*MockILogger)(nil).WarnKV), varargs...)
}
