// Code generated by MockGen. DO NOT EDIT.
// Source: postgres.go

// Package postgres is a generated GoMock package.
package postgres

import (
	context "context"
	sql "database/sql"
	reflect "reflect"
	sqlc "subscription-vault-service/internal/clients/postgres/sqlc"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockIQuerier is a mock of IQuerier interface.
type MockIQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockIQuerierMockRecorder
}

// MockIQuerierMockRecorder is the mock recorder for MockIQuerier.
type MockIQuerierMockRecorder struct {
	mock *MockIQuerier
}

// NewMockIQuerier creates a new mock instance.
func NewMockIQuerier(ctrl *gomock.Controller) *MockIQuerier {
	mock := &MockIQuerier{ctrl: ctrl}
	mock.recorder = &MockIQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIQuerier) EXPECT() *MockIQuerierMockRecorder {
	return m.recorder
}

// CreateSubscription mocks base method.
func (m *MockIQuerier) CreateSubscription(ctx context.Context, arg sqlc.CreateSubscriptionParams) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubscription", ctx, arg)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubscription indicates an expected call of CreateSubscription.
func (mr *MockIQuerierMockRecorder) CreateSubscription(ctx, arg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubscription", reflect.TypeOf((*MockIQuerier)(nil).CreateSubscription), ctx, arg)
}

// MockIDB is a mock of IDB interface.
type MockIDB struct {
	ctrl     *gomock.Controller
	recorder *MockIDBMockRecorder
}

// MockIDBMockRecorder is the mock recorder for MockIDB.
type MockIDBMockRecorder struct {
	mock *MockIDB
}

// NewMockIDB creates a new mock instance.
func NewMockIDB(ctrl *gomock.Controller) *MockIDB {
	mock := &MockIDB{ctrl: ctrl}
	mock.recorder = &MockIDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDB) EXPECT() *MockIDBMockRecorder {
	return m.recorder
}

// CtxWithCancel mocks base method.
func (m *MockIDB) CtxWithCancel() (context.Context, context.CancelFunc) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CtxWithCancel")
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(context.CancelFunc)
	return ret0, ret1
}

// CtxWithCancel indicates an expected call of CtxWithCancel.
func (mr *MockIDBMockRecorder) CtxWithCancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CtxWithCancel", reflect.TypeOf((*MockIDB)(nil).CtxWithCancel))
}

// ExecTx mocks base method.
func (m *MockIDB) ExecTx(arg0 *sql.TxOptions, arg1 func(context.Context, IQuerier) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecTx", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecTx indicates an expected call of ExecTx.
func (mr *MockIDBMockRecorder) ExecTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecTx", reflect.TypeOf((*MockIDB)(nil).ExecTx), arg0, arg1)
}

// Querier mocks base method.
func (m *MockIDB) Querier() IQuerier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Querier")
	ret0, _ := ret[0].(IQuerier)
	return ret0
}

// Querier indicates an expected call of Querier.
func (mr *MockIDBMockRecorder) Querier() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Querier", reflect.TypeOf((*MockIDB)(nil).Querier))
}
